### ISSUE TITLE
Matterbridge doesnt start

### ISSUE THREAD

**Issue by enslaved2die** [t0bst4r/matterbridge-home-assistant-addon#62] opened 2024-06-20 10:55 UTC
I get this error in the logs and the matterbridge never starts
First I thought this is the same issue with the climate entity so I only added lights to the list but still doesnt start.
Also reinstalling didnt work

> CLI: Matterbridge.loadInstance() failed with error: Error: [node-persist][readFile] /root/.matterbridge/storage/.matterbridge/d01917a070027b55bce538a96fa2004f061de6fe1644f402a321c6db8c71b9ba does not look like a valid storage file!
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by t0bst4r** [comment] 2024-06-20 11:09
Duplicate of #59

**Closed by t0bst4r** 2024-06-20 11:09 UTC
